# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import TransferService_pb2 as TransferService__pb2


class TransferServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.transfer = channel.unary_unary(
        '/com.example.grpc.TransferService/transfer',
        request_serializer=TransferService__pb2.TransferRequest.SerializeToString,
        response_deserializer=TransferService__pb2.TransferResponse.FromString,
        )


class TransferServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def transfer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TransferServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'transfer': grpc.unary_unary_rpc_method_handler(
          servicer.transfer,
          request_deserializer=TransferService__pb2.TransferRequest.FromString,
          response_serializer=TransferService__pb2.TransferResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.example.grpc.TransferService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
